# Generated by Django 5.0.1 on 2024-01-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="status",
            field=models.CharField(default="inactive", max_length=30),
            preserve_default=False,
        ),
    ]
