# Generated by Django 5.0.1 on 2024-02-26 09:43

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyUserProfile",
            fields=[],
            options={
                "ordering": ["pancard"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("app1.userprofile",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
