# Generated by Django 5.0.3 on 2024-03-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.IntegerField()),
                ("b", models.IntegerField()),
                ("c", models.IntegerField()),
            ],
        ),
    ]
